status = warn
rootLogger.level = INFO
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = Console

appender.console.type = Console
appender.console.name = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %-5p %c{2} - %m%n

logger.hs2.name = org.apache.hive.service.server
logger.hs2.level = INFO
logger.thrift.name = org.apache.hive.service.cli.thrift
logger.thrift.level = INFO
